# ~/dotfiles/config/alacritty/alacritty.toml

[general]
import = []
live_config_reload = true
ipc_socket = true

[window]
title = "myrn"
decorations = "Full"
startup_mode = "Windowed"
opacity = 0.8 
padding = { x = 0, y = 0 }
dynamic_padding = true

[scrolling]
history = 10000
multiplier = 3

[font]
size = 12.0
normal = { family = "FiraCode Nerd Font", style = "Regular" }
bold = { family = "FiraCode Nerd Font", style = "Bold" }
italic = { family = "FiraCode Nerd Font", style = "Italic" }
bold_italic = { family = "FiraCode Nerd Font", style = "Bold Italic" }
offset = { x = 0, y = 0 }


[cursor]
style = { shape = "Block", blinking = "On" }
thickness = 0.15

[terminal]
osc52 = "CopyPaste"

[mouse]
hide_when_typing = true

[keyboard]
bindings = [
    { key = "NumpadEnter", chars = "\r" },
    
    { key = "Plus", mods = "Control", action = "IncreaseFontSize" },
    { key = "Minus", mods = "Control", action = "DecreaseFontSize" },
    { key = "Key0", mods = "Control", action = "ResetFontSize" },
    
    { key = "N", mods = "Control|Shift", action = "SpawnNewInstance" },
    
    { key = "C", mods = "Control|Shift", action = "Copy" },
    { key = "V", mods = "Control|Shift", action = "Paste" }
]

[colors.primary]
background = "#000000"
foreground = "#FFFFFF"

[colors.normal]
black = "#181818"
red = "#FF2F48"
green = "#0AFF00"
yellow = "#FFFF55"
blue = "#0010FF"
magenta = "#008787"
cyan = "#A4D111"
white = "#ffffff"

[colors.bright]
black = "#6b6b6b"
red = "#FF2F48"
green = "#aac474"
yellow = "#FFFF55"
blue = "#00B4FF"
magenta = "#008787"
cyan = "#A4D111"
white = "#ffffff"
